# 示例配置文件 config.yml

server:
  port: 8080          # 应用程序端口

database:
  url: jdbc:mysql://localhost:3306/mydatabase  # 数据库连接 URL
  username: root                             # 数据库用户名
  password: password                          # 数据库密码

logging:
  level: INFO         # 日志级别 (DEBUG, INFO, WARN, ERROR)

application:
  name: MySpringApp   # 应用程序名称
  version: 1.0.0      # 应用程序版本
  environment: dev    # 应用程序环境 (dev, prod, test, etc.)

